### PR TITLE
Update reduction count to 4K

### PR DESCRIPTION
**Pull request by hirotnk**

### CODE REVIEW

**Comment by kvakvs** [comment]
Please keep both old and new value and at least major version when it was changed. Old value still is "valuable" 😀

**Comment by hirotnk** [comment]
@kvakvs Thank you for the review, how about introducing some format that can be used in everywhere in the document for similar situations? For example, Erlang doc has info for APIs since when it was introduced or modified like `OTP R13B04`.
Also, I wish we could introduce some variables to be referenced from multiple places in the document so that we don't have to modify multiple times.

**Comment by happi** [comment]
Yes, let us continue the versioning question in your previous issue #77 and just add a note here.

Thanks for the contribution.

**Comment by hirotnk** [comment]
@happi @kvakvs Added link to the source and note. On my local, it looks like:
Screen Shot 2020-03-07 at 20 02 04
and 
Screen Shot 2020-03-07 at 20 02 50

**Comment by hirotnk** [comment]
I also tried differently:
Screen Shot 2020-03-07 at 20 59 41
and 
Screen Shot 2020-03-07 at 20 59 53

Please let me know which is better, or if there is any suggestion. I'll make a change accordingly.

**Comment by happi** [comment]
I like the one with the “version info” title.

**Comment by hirotnk** [comment]
@happi Updated.

**Comment by happi** [comment]
Thanks.

Remind me to do a new release soon. I should take the time and do some other fixes also.

**Comment by hirotnk** [comment]
Great, thank you too!

**Pull request merged**
