### PR TITLE
Migrate pdf format

### PR DESCRIPTION
**Pull request by hirotnk**
This PR is an attempt to improve maintainability by introducing the usage of [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf) instead of dblatex to generate pdf file. Since both `asciidoctor` and `asciidoctor-pdf` are under the same project, it's easier to use both together, and they are actively maintained, and easy to customize a variety of features.

Alongside the migration of pdf generator, this PR introduced/improved the following items:
- Usage of [ditaa](https://github.com/stathissideris/ditaa) instead of [shaape](https://github.com/christiangoltz/shaape) to generate diagram image from ascii art. This was made because shaape is not maintained since 2014.
- Use Unicode characters directly in `asciidoc` documents - since `asciidoctor` and `asciidoctor-pdf` both understand UTF-8, no need for extra work for both tools(`asciidoc` and dblatex) to deal with Unicode character sets. I think this would make it easier to resolve issues like https://github.com/happi/theBeamBook/issues/124
- Introduce new Admonition `VERSION` to indicate version info of OTP for each sections, related to https://github.com/happi/theBeamBook/issues/77
- Update header/footer in pdf
- Fix Appendix structure

This is still WIP, and I'd like to get some feedback to work further.

Also, I appreciate my current employer [TubiTV](https://tubitv.com/) for allowing me to work on this for 2 days as part of our second annual "oss-a-thon" event.

### CODE REVIEW

**Comment by happi** [comment]
First impression: Nice!

**Comment by happi** [comment]
The new style and format of the PDF looks really nice, especially the new diagrams are nice.
I think the compiler passes figure, Figure 6, would look better without bold for the lables, they are a bit to close vertically.

**Comment by happi** [comment]
Figure 25(Port Communication)  might need some changes to work nicely with ditaa.

**Comment by happi** [comment]
All in all much needed improvements.

**Comment by happi** [comment]
While you are at it, a list of instructions for installing build tools for linux might be a good idea. If you don't have access to a Linux/Ubuntu system I can fix that after merge.

**Comment by hirotnk** [comment]
@happi Thank you for your feedback, I will work on your comments and update here once I'm done.

**Comment by hirotnk** [comment]
@happi Updated:
- README to include `rouge` syntax highlighter, and other instructions. For Linux, I don't have access right now but it won't be much trouble since we have the asciidoctor [public docker image](https://github.com/asciidoctor/docker-asciidoctor)
- Figures - Compiler passes and Figure 25(Port Communication)
- Makefile
- Fix links to AP-xxx
- .travis.yml (not sure if it will work yet)

I'm sure there are still lots of errors, please let me know if you want to fix something.

**Comment by happi** [comment]
Great work!

**Pull request merged**
