### PR TITLE
Add missing erlang to execute erl command

### PR DESCRIPTION
**Pull request by hirotnk**
I wanted to [debug the Travis error](https://docs.travis-ci.com/user/build-config-validation/), but it seems not activated ? Maybe we could activate it.
> To enable debug for your public repositories, please email us at support@travis-ci.com and let us know which repositories you want activated.

~How about making builds enabled (without deployment, of course) for each PR in the future ?~
Oh it's already doing it :-)

### CODE REVIEW

**Comment by happi** [comment]
You should be a collaborator now, feel free to merge yourself to get the pipeline to run.

**Comment by happi** [comment]
Let me know if I need to set up the pipeline for PRs or if you can do that.

**Comment by hirotnk** [comment]
@happi , Thank you, will do.

**Comment by happi** [comment]
Do you have my email?

**Comment by hirotnk** [comment]
Yes, hirotnkg@gmail.com

**Comment by hirotnk** [comment]
I don't have your email.

**Comment by happi** [comment]
I invited you to the beam book slack. It's happi@happihacking.com

**Comment by hirotnk** [comment]
Great, thank you!

**Comment by happi** [comment]
Should I rebase and merge or are you doing that?

**Comment by hirotnk** [comment]
Let me do that.

**Pull request merged**
