### PR TITLE
Nit fixed link text in README

### PR DESCRIPTION
**Pull request by sthagen**
... for asciidoctor-pdf (docker image)

From reading the documentation, thought I offer a quick fix (not important).

In case this helps, glad to have it merged, in case you decide to not include, no hard feelings.

All the best,
Stefan

### CODE REVIEW

**Comment by sthagen** [comment]
Note: travis seems to not be helpful anymore for open source, the failure is travis system installing the docker image for ascidoctor-pdf. They will shut down the org site soon, and to my knowledge no pro bono plan is public for open source projects.

No promises, but I might be able to help migrating the workflow to GitHub actions (if me, willing to invest some time on that move is considered beneficial).

**Review by happi — APPROVED** [review]

**Comment by happi** [comment]
It would be very helpful if we could use Github actions instead.

**Comment by happi** [comment]
Thanks for the typo fix.

**Comment by sthagen** [comment]
> It would be very helpful if we could use Github actions instead.

I will try to propose per my fork ... on another happy ERLEF day :wink:

**Pull request merged**
